[WIP] Feat/plugin ssr
ice-lab/icejs pull request #117
Opened 2020-03-16 11:37 UTC by chenbin92

2020-03-18 09:21 UTC, chenbin92 commented
## 问题：
1. 全局变量名优化
```ts
__ICE_APP_DATA__
__ICE_PAGE_PROPS_
```
2. 动态改了 js 里的代码，刷新 HTML 不生效，重新 start 才能生效

2020-03-19 02:51 UTC, ClarkXia commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  if (!process.env.__IS_SSR__) {
createApp 只处理非 SSR 场景？

2020-03-19 02:51 UTC, ClarkXia commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +        ReactDOM[process.env.__IS_SSR__ ? 'hydrate' : 'render'](<App />, appMountNode, () => {
进到这段逻辑的时候 `process.env.__IS_SSR__` 永远是 false

2020-03-19 02:51 UTC, ClarkXia commented on packages/plugin-core/src/index.ts
> +import * as webpack from 'webpack'
webpack 从 context 上取

2020-03-19 02:51 UTC, ClarkXia commented on packages/plugin-core/src/index.ts
> +      .plugin('DefinePlugin')
默认应该有 DefinePlugin 的注册，有一些默认值，可以用修改参数的方式

2020-03-19 02:51 UTC, ClarkXia commented on packages/plugin-router/src/module.tsx
> +      context
这里的 context 没看到哪里用到了

2020-03-19 02:51 UTC, ClarkXia commented on packages/plugin-ssr/src/index.ts
> +require('babel-polyfill')
为什么需要 babel-polyfill

2020-03-19 02:51 UTC, ClarkXia commented on packages/plugin-ssr/src/index.ts
> +  const content = ejs.render(templateContent, { htmlStr: JSON.stringify(htmlStr), importAppStr })
需要看下 win 下是不是会有路径问题

2020-03-19 03:41 UTC, chenbin92 commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  if (!process.env.__IS_SSR__) {
1. createApp 提供给客户端调用，只接收 appConfig
2. createAppWithSSR 提供给服务端调用，接收 appConfig 和  context（initialData/pageInitialProps/pathname）

2020-03-19 03:42 UTC, chenbin92 commented on packages/plugin-core/src/index.ts
> +      .plugin('DefinePlugin')
怎么修改

2020-03-19 03:46 UTC, chenbin92 commented on packages/plugin-core/src/index.ts
> +      .plugin('DefinePlugin')
怎么修改

2020-03-19 04:00 UTC, chenbin92 commented on packages/plugin-core/src/index.ts
> +      .plugin('DefinePlugin')
![image](https://user-images.githubusercontent.com/3995814/77030334-35397880-69d9-11ea-8450-f80ea3d5c619.png)

2020-03-19 04:08 UTC, chenbin92 commented on packages/plugin-core/src/index.ts
> +import * as webpack from 'webpack'
fixed

2020-03-19 04:09 UTC, chenbin92 commented on packages/plugin-router/src/module.tsx
> +      context
删除了

2020-03-19 04:09 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +require('babel-polyfill')
删除了

2020-03-19 04:09 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +  const content = ejs.render(templateContent, { htmlStr: JSON.stringify(htmlStr), importAppStr })
加了 formatPath

2020-03-19 04:28 UTC, chenbin92 commented on packages/plugin-core/src/index.ts
> +      .plugin('DefinePlugin')
改了，单独注册的 ssr 里面没有配置过 defineplugin 还是需要这么写

2020-03-19 05:01 UTC, imsobear commented
plugin-ssr 依赖记得加进去

2020-03-19 07:32 UTC, chenbin92 commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +        ReactDOM[process.env.__IS_SSR__ ? 'hydrate' : 'render'](<App />, appMountNode, () => {
window.__ICE_SSR__=ture

2020-03-19 08:33 UTC, imsobear requested changes

2020-03-19 08:33 UTC, imsobear commented on packages/icejs/src/index.ts
> +
如之前的沟通，这两个逻辑一致化下

2020-03-19 08:33 UTC, imsobear commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +function createAppWithSSR(customConfig, context = {}) {
context 的类型声明下

2020-03-19 08:33 UTC, imsobear commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  __APP_CONFIG__ = appConfig
这里才赋值的话，server 里能拿到吗？感觉不太对呀

2020-03-19 08:33 UTC, imsobear commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  }
这里的逻辑我感觉不太对呀，应该是：

```js
if (开启了 SSR) {
   if (在服务端渲染) {
      // 啥都不用做
   } else {
       // 浏览器端渲染
      // 把 window 上的数据赋值给 context
   }
} else {
  // 没开启 SSR，浏览器端直接获取
  // 调用 getInitialData
}
```

2020-03-19 08:33 UTC, imsobear commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  if (process.env.__IS_SSR__) {
这里应该是 `isServerRender` 而不是 isSSR 吧

2020-03-19 08:43 UTC, chenbin92 commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  __APP_CONFIG__ = appConfig
能拿到

2020-03-19 08:47 UTC, chenbin92 commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  if (process.env.__IS_SSR__) {
`__IS_SSR__ ` 在 ssr 任务里进行了注册，不需要从 server 层层透传

2020-03-19 09:17 UTC, chenbin92 commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  }
命名优化了下

2020-03-19 09:18 UTC, chenbin92 commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +function createAppWithSSR(customConfig, context = {}) {
加上了

2020-03-19 09:42 UTC, imsobear commented on packages/icejs/src/index.ts
> +  if (typeof userConfig.store === 'undefined' || userConfig.store !== false) {
用 hasOwnProperty 更安全点？

2020-03-19 09:43 UTC, chenbin92 commented on packages/icejs/src/index.ts
> +
改了

2020-03-19 10:03 UTC, imsobear requested changes

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  }
这里的几个分支写下注释吧

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-router/src/runtime/Router.tsx
> +            const RenderComponent = process.env.__IS_SERVER__ || process.env.__SSR_ENABLED__
__SSR_ENABLED__ 的情况为什么要干掉 suspense？

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +      }
这个 diff 怎么到这里来了，没更新代码？

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +}
这个我建议直接在 wrapperPage 里面处理掉，防止未来两边逻辑不同步

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-ssr/src/index.ts
> +  const buildDir = path.resolve(rootDir, 'build')
这里不应该写死

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-ssr/src/index.ts
> +      'process.env.__IS_SERVER__': true
加下： __SSR_ENABLED__: true

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-ssr/src/index.ts
> +      .path(buildDir)
如上，output 应该与主任务保持一致

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-ssr/src/index.ts
> +      .filename('server.js')
server/xxx.js，放到 server 目录下

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-ssr/src/index.ts
> +  const htmlStr = fse.readFileSync(path.join('public', 'index.html'), 'utf8')
vendor 之类的是不是丢了？

2020-03-19 10:03 UTC, imsobear commented on packages/plugin-ssr/src/server.ts.ejs
> +  $('body').append(`<script src="/js/index.js"></script>`)
跟上面 vendor 一个问题，这个 html 还是要想办法读取主任务构建出来的结果

2020-03-19 10:10 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +      .filename('server.js')
就一个文件，感觉不太需要？

2020-03-19 10:14 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +      'process.env.__IS_SERVER__': true
加了的作用是？我理解：
1. 如果是 `ssr: true`，那么在主任务就是 `process.env. SSR_ENABLED=true`
2. 如果是 `ssr: false`，那么也进不到 ssr 这个任务了

2020-03-19 10:15 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +      .path(buildDir)
html 这个现在还没有好的办法拿到，就剩下这个在处理了

2020-03-19 10:16 UTC, chenbin92 commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +}
这个有个 MR 优化时特意拆分写的，感觉这样逻辑会更清晰一点，本身逻辑也不太一样？

2020-03-19 10:17 UTC, chenbin92 commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +      }
合并冲突产生的

2020-03-19 10:19 UTC, chenbin92 commented on packages/plugin-router/src/runtime/Router.tsx
> +            const RenderComponent = process.env.__IS_SERVER__ || process.env.__SSR_ENABLED__
这是个好问题。

- `process.env.__IS_SERVER__` 对应的是  `React.RenderToString()` 是去掉 suspense
- `process.env.__SSR_ENABLED__ ` 对应的是 `React.hydrate()` 时去掉 suspense

2020-03-19 10:22 UTC, chenbin92 commented on packages/plugin-router/src/runtime/Router.tsx
> +            const RenderComponent = process.env.__IS_SERVER__ || process.env.__SSR_ENABLED__
`React.RenderToString()` 和 `React.hydrtate()` 都不能有 suspense，或者会导致两次对比检查不一致，hydrate 不了，会出现以下错误

![image](https://user-images.githubusercontent.com/3995814/77057176-8879ee00-6a0e-11ea-9443-2bc6f3920538.png)


* https://stackoverflow.com/questions/45350360/react-16-warning-warning-js36-warning-did-not-expect-server-html-to-contain-a

2020-03-19 10:34 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +  const htmlStr = fse.readFileSync(path.join('public', 'index.html'), 'utf8')
html 这个现在还没有好的办法拿到，就剩下这个在处理了

2020-03-19 10:36 UTC, imsobear commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  }
考虑按照下面的方式优化下（逻辑+注释）：

```js
function createApp(customConfig: IAppConfig) {
  const appConfig = deepmerge(defaultAppConfig, customConfig)	  const appConfig = deepmerge(defaultAppConfig, customConfig)
  
  if (process.env.__IS_SERVER__) {
    // SSR 时服务端 entry 通过调用 createApp 获取 appConfig
    process.env.__APP_CONFIG__ = appConfig;
    return;
  }

  // 浏览器端渲染
  
  const runtime = new RuntimeModule(appConfig, <%- buildConfig %>)	__APP_CONFIG__ = appConfig
  let initialData = {}
  let pageInitialProps = {}
  if (window.__ICE_APP_DATA__) {
    // 开启了 SSR 并且服务端已直出了数据
    initialData = window.__ICE_APP_DATA__
    pageInitialProps = window.__ICE_PAGE_PROPS__
    renderApp(appConfig, { initialData, pageInitialProps })
  } else {
    // 未开启 SSR
    if (appConfig.app.getInitialData) {
      (async() => {
        initialData = await appConfig.app.getInitialData()
        renderApp(appConfig, { initialData, pageInitialProps })
      })()
    } else {
      renderApp(appConfig)
    }
  }
}
```

2020-03-19 10:38 UTC, imsobear commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  }
`import __APP_CONFIG__` 改成 `process.env.__APP_CONFIG__`

2020-03-19 10:42 UTC, imsobear commented on packages/plugin-ssr/src/server.ts.ejs
> +<%- importAppStr %>
是不是可以直接 `import '@/app';`？

2020-03-19 10:44 UTC, imsobear commented on packages/plugin-router/src/runtime/Router.tsx
> +            const RenderComponent = process.env.__IS_SERVER__ || process.env.__SSR_ENABLED__
OK，没有问题

2020-03-19 10:47 UTC, imsobear commented on packages/plugin-ssr/src/index.ts
> +      'process.env.__IS_SERVER__': true
对齐一下，代码可读性好一点

2020-03-19 10:48 UTC, imsobear commented on packages/plugin-ssr/src/index.ts
> +      .filename('server.js')
扩展性（比如 MPA？），像现在 css js 都是单独目录，server 我建议还是单独目录吧

2020-03-19 10:50 UTC, imsobear commented on packages/plugin-ssr/src/index.ts
> +  const htmlStr = fse.readFileSync(path.join('public', 'index.html'), 'utf8')
我理解跟我 FaaS 那个一样处理就可以了吧，主任务开启 writeDisk，SSR 任务从 `build/index.html` 读取，唯一可能有问题的就是时机问题，这个要确认下

2020-03-19 10:53 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +}
分开也可以，但是这个就应该叫 wrapperPageInServer ？

2020-03-19 10:55 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +  const WrapperedPage = (props) => {
不要乱改哦，这个在开发者工具里面可以看到，具名的更方便调试

2020-03-19 10:56 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +    const WrapperedPage = (props) => {
建议优化成 ServerWrapperedPage

2020-03-19 10:57 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +        (window as any).__ICE_PAGE_PROPS__ = null
加下注释，为什么要清除

2020-03-19 10:58 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +  });
需要递归下吧

2020-03-19 10:58 UTC, imsobear commented on packages/plugin-ssr/src/server.ts.ejs
> +  });
这个也需要递归下

2020-03-19 12:15 UTC, imsobear commented on packages/plugin-ssr/src/server.ts.ejs
> +<%- importAppStr %>
这个不关键。。后面做 MPA 的话还是得传

2020-03-19 12:18 UTC, chenbin92 commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  }
这个不太适合用`process.env` 挂载，appConfig 不是简单的字符串，还有函数提，需要用类似 `serialize-javascript` 这样的序列号，使用的时候还得反序列化。

2020-03-19 12:52 UTC, imsobear commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  }
服务端的时候 process.env 上可以挂载任何东西

2020-03-19 13:19 UTC, chenbin92 commented on packages/plugin-core/src/generator/templates/app/createApp.tsx.ejs
> +  }
![image](https://user-images.githubusercontent.com/3995814/77071568-3e513680-6a27-11ea-929b-c11c38770ee3.png)

https://nodejs.org/api/process.html#process_process_env

2020-03-19 13:21 UTC, chenbin92 commented on packages/icejs/src/index.ts
> +  if (typeof userConfig.store === 'undefined' || userConfig.store !== false) {
hasOwnProperty 也有隐含的问题，改成 `Object.prototype.hasOwnProperty.call)` 了

2020-03-19 13:23 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +      .path(buildDir)
fixed

2020-03-19 13:23 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +      'process.env.__IS_SERVER__': true
fixed

2020-03-19 13:23 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +      .filename('server.js')
fixed

2020-03-19 13:27 UTC, chenbin92 commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +  const WrapperedPage = (props) => {
现在也是具名的，当时特意改动感觉 WrapperedPage 命名会更语义

![image](https://user-images.githubusercontent.com/3995814/77072319-786f0800-6a28-11ea-87fc-878d7b494443.png)

2020-03-19 14:26 UTC, imsobear commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +  const WrapperedPage = (props) => {
那就到处都变成了 WrapperedPage。。。没有意义了

2020-03-20 01:39 UTC, chenbin92 commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +  const WrapperedPage = (props) => {
改了

2020-03-20 01:39 UTC, chenbin92 commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +    const WrapperedPage = (props) => {
改了

2020-03-20 01:39 UTC, chenbin92 commented on packages/plugin-router/src/runtime/formatRoutes.tsx
> +        (window as any).__ICE_PAGE_PROPS__ = null
加上了

2020-03-20 02:31 UTC, imsobear requested changes

2020-03-20 02:31 UTC, imsobear commented on packages/icejs/src/index.ts
> +  if (!Object.prototype.hasOwnProperty.call(userConfig, "store") || userConfig.store !== false) {
"store" => 'store'

2020-03-20 02:31 UTC, imsobear commented on packages/plugin-router/src/runtime/Router.tsx
> +            const RenderComponent = process.env.__IS_SERVER__ || process.env.__SSR_ENABLED__
加个注释

2020-03-20 02:31 UTC, imsobear commented on packages/plugin-ssr/src/index.ts
> +  const buildDir = path.resolve(rootDir, userConfig.outputDir, 'server')
这样处理不够完备但暂时也可以，比如通过插件而非 userConfig 自定义 output 的情况，没好的办法就先加个 TODO 的注释。

方案不求完备，但存在的问题要能想到哈。

2020-03-20 06:36 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +  const buildDir = path.resolve(rootDir, userConfig.outputDir, 'server')
加了说明

2020-03-20 06:36 UTC, chenbin92 commented on packages/plugin-ssr/src/index.ts
> +  const htmlStr = fse.readFileSync(path.join('public', 'index.html'), 'utf8')
已处理

2020-03-20 08:07 UTC, merged