fix: add History types
ice-lab/icejs pull request #215
Opened 2020-04-04 14:20 UTC by chenbin92

2020-04-04 16:04 UTC, imsobear commented on packages/plugin-router/src/types/index.ts
> +import { History } from 'history';
history 不是 plugin-core 依赖的吗？这样搞的话依赖乱掉了，这个问题要多关注下呀

2020-04-06 09:12 UTC, chenbin92 commented on packages/plugin-router/src/types/index.ts
> +import { History } from 'history';
在 plugin-core 里设置了 `react/react-dom/react-router-dom`  alias，保证了所有模块使用都是同一个依赖，history 是 react-router-dom 的依赖插件里没有单独依赖

2020-04-06 09:21 UTC, imsobear commented on packages/plugin-router/src/types/index.ts
> +import { History } from 'history';
直接使用依赖的依赖应该是不推荐的做法吧？感觉有点隐患

2020-04-06 09:32 UTC, chenbin92 commented on packages/plugin-router/src/types/index.ts
> +import { History } from 'history';
更新了

1. 将 `react-router-dom/history` 相关的操作统一到 plugin-router 中
2. 导出 `createHashHistory/createBrowserHistory/createMemoryHistory` 接口
3. 显示添加 `history` 依赖

2020-04-06 10:17 UTC, imsobear requested changes

2020-04-06 10:17 UTC, imsobear commented on packages/plugin-router/templates/index.ts
> +export * from './history';
下面这一句的目的是？

2020-04-06 10:17 UTC, imsobear commented on packages/plugin-router/src/types/index.ts
> +import { History } from 'history';
现在 src/routes 没有类型支持，如果要支持的话怎么搞（跟 IAppConfig 一样）？IRenderRouteProps 这个内容是不是得往 templates 里再 copy 一份？

2020-04-06 10:17 UTC, imsobear commented on packages/plugin-router/templates/index.ts
> +export * from './history';
业务代码里 `import { createBrowserHistory } from 'ice'` 吗？

2020-04-06 10:17 UTC, imsobear commented on packages/plugin-router/templates/history.ts
> +export * from 'history';
建议按需 export，否则 `ice` 里的内容要爆炸了。

2020-04-06 10:17 UTC, imsobear commented on packages/plugin-router/templates/history.ts
> +export * from 'history';
能从 `ice` 里 import 哪些东西应该是明确具体的。

2020-04-06 10:17 UTC, imsobear commented on packages/plugin-core/package.json
> -    "react-router-dom": "^5.1.2"
core 里面有个 alias react-router-dom 的逻辑，应该要移动到 router 里？

2020-04-06 10:19 UTC, chenbin92 commented on packages/plugin-router/templates/index.ts
> +export * from './history';
是的，router 提供了 history 对象的配置，所以考虑 ice 提供相关的 API

2020-04-06 10:26 UTC, chenbin92 commented on packages/plugin-router/templates/history.ts
> +export * from 'history';
写的时候看了相关 API 如下，考虑尽量与 history 包提供的 API 保持一致导出。

![image](https://user-images.githubusercontent.com/3995814/78548379-4a186780-7833-11ea-81fd-c9556654c33d.png)

2020-04-06 10:27 UTC, chenbin92 commented on packages/plugin-router/templates/history.ts
> +export * from 'history';
最后两行 API 先不提供吧，等有诉求在按需追加，保持「最小可用原则」

2020-04-06 10:31 UTC, chenbin92 commented on packages/plugin-router/templates/history.ts
> +export * from 'history';
fixed，只导出了 createXxxHistory 三个 API

2020-04-06 10:38 UTC, chenbin92 commented on packages/plugin-router/src/types/index.ts
> +import { History } from 'history';
1. 和 IAppConfig 不同意义，IAppConfig 是多个插件动态组合的一个接口
2. 单个插件需要导出的接口方式如下：
```ts
// 插件
// 该接口会往 .ice/types.ts 里插入一条导出语句，如下
applyMethod('addIceTypesExport', { source: '@ice/store/lib/types' });
// export * from '@ice/store/lib/types';

// .ice/index.ts
在 .ice/index.ts 中会导出 types.ts 中的所有类型
export * from './types';
```

2020-04-06 10:41 UTC, chenbin92 commented on packages/plugin-core/package.json
> -    "react-router-dom": "^5.1.2"
这种感觉还是放在 plugin-core 里集中维护会比较好一点？逻辑太分散也有维护成本

2020-04-06 10:44 UTC, imsobear commented on packages/plugin-core/package.json
> -    "react-router-dom": "^5.1.2"
core 没依赖 router，拿到的 path 会不准确，要么你就依赖一起放 core 里

2020-04-06 10:46 UTC, chenbin92 commented on packages/plugin-router/src/types/index.ts
> +import { History } from 'history';
这块单独记个 issue 统一导出下，目前只处理了 IAppConfig 的类型 https://github.com/ice-lab/icejs/issues/217

2020-04-06 10:48 UTC, imsobear commented on packages/plugin-router/src/types/index.ts
> +import { History } from 'history';
上面这个逻辑我知道，我意思 `IRouterConfig` 这个类型具体要怎么搞，看样子是要写两份，具体在你单独拿个 issue 里讨论

2020-04-06 11:00 UTC, imsobear commented on packages/plugin-router/templates/history.ts
> +export * from 'history';
没看到。。。

2020-04-06 11:05 UTC, chenbin92 commented on packages/plugin-router/templates/history.ts
> +export * from 'history';
上面截图是 history 的 index.js 导出的

2020-04-06 11:46 UTC, chenbin92 commented on packages/plugin-core/package.json
> -    "react-router-dom": "^5.1.2"
fixed

2020-04-06 12:07 UTC, merged