feat: add ErrorBoundary component
ice-lab/icejs pull request #233
Opened 2020-04-09 10:09 UTC by chenbin92

fix issue: https://github.com/ice-lab/icejs/issues/213

2020-04-09 14:59 UTC, imsobear commented
页面级别是不是可以支持下？比如通过 pageConfig 开启？

2020-04-10 02:33 UTC, chenbin92 commented
> 页面级别是不是可以支持下？比如通过 pageConfig 开启？

可以支持下，配置如下：

```ts
HomePage.pageConfig = {
   errorBoundary:  boolean
}
```

 ErrorBoundary 粒度主要有「应用级别」、「页面级别」、「组件级别」三种
- [x] 应用级别：最后的兜底
- [ ] 页面级别：在有 Layout 的情况下会比较合适
- [x] 组件级别：使用框架提供的 ErrorBoundary 和 withErrorBoundary 进行自定义

2020-04-16 12:11 UTC, ClarkXia requested changes

2020-04-16 12:11 UTC, ClarkXia commented on packages/plugin-core/src/module.tsx
> +        <ErrorBoundary>
页面级别的 error fallback 怎么定义

2020-04-16 12:55 UTC, imsobear approved these changes

2020-04-16 13:11 UTC, ClarkXia approved these changes

2020-04-16 13:41 UTC, merged