feat: support lazy store
ice-lab/icejs pull request #236
Opened 2020-04-12 15:38 UTC by chenbin92

## 需求

- [x] 支持 store 按需加载 https://github.com/ice-lab/icejs/issues/79
- [x]  https://github.com/ice-lab/icejs/issues/120

## 方案

### 目录结构

```markdown
.ice/pages/HomePage
  ├── Home.tsx  // 引入 store
  ├── index.ts  // 入口文件
  └── store.ts  // 创建 store
```

### Home.tsx

新生成 `.ice/pages/${pageName}.tsx`并在该文件引入 store

```tsx
// .ice/pages/Home/Home.tsx
import * as React from 'react';
import Home from '/Users/xxx/examples/src/pages/Home';
import store from './store';

export default () => {
  return (
    <store.Provider>
      <Home />
    </store.Provider>
  )
}
```

### store.ts

创建页面级别的 `store.ts`

```
import { createStore } from '@ice/store';
import Home from '/Users/xxx/examples/src/pages/Home/model';

const model = { default: Home };
const store = createStore(model);
export default store;

```

### 修改 plugin-store 的 Model
- [x] 删除 pageStores 逻辑
- [x] 删除 plugin-store/module.tsx 下的 PageProvider 注册逻辑
- [x] 将 appStore 移到 store 目录下优化生成目录结构
- [x] appConfig 的 initialStates 逻辑不变
- [x] 验证 appConfig
- [ ] 约定式路由改造 @ => ice

### 用户代码变更
- [ ] 通过 AST 修改 @ => ice

2020-04-14 09:22 UTC, ClarkXia commented on packages/plugin-store/src/babelPluginReplacePath.ts
> +            if (typeof value === 'string') {
需要判断 callee 是 import 再进行后续处理

2020-04-14 09:22 UTC, ClarkXia commented on packages/plugin-store/src/babelPluginReplacePath.ts
> +            if (value.startsWith("@/pages") || value.startsWith("../pages")) {
这块还要考虑到 alias 定制和 route file 路径的定制

2020-04-14 09:31 UTC, ClarkXia commented on packages/plugin-store/src/index.ts
> +  const routeFile = hasRouteFile ? routeConfigPath : routeTempPath;
router 相关逻辑需要抽离下，现在跟 plugin-router 重复

2020-04-14 09:31 UTC, ClarkXia commented
涉及到 store 文件的动态生成，需要 check 下 watch 的逻辑

2020-04-14 13:06 UTC, chenbin92 commented on packages/plugin-store/src/babelPluginReplacePath.ts
> +            if (value.startsWith("@/pages") || value.startsWith("../pages")) {
### 默认：`src/routes.ts`

```ts
// 配置式：
import Home from './pages/Home';
import Home from '@/pages/Home';

// 配置式：lazy
const Home = lazy(() => import('./pages/Home'));
const Home = lazy(() => import('@/pages/Home'));

// 约定式：
import Home from '../src/pages/Home/index.tsx';

// 约定式：lazy
const Home = lazy(() => import('../pages/Home'));
```

### 自定义：

```ts
// 场景一：src/config/routes.ts
import Home from '../pages/Home'

// 场景二：src/config/xx/routes.ts
import Home from '../../pages/Home'

// 场景三：src/pages/Home/routes.ts
import Home from './index'
```

2020-04-15 06:06 UTC, chenbin92 commented on packages/plugin-store/src/index.ts
> +  const routeFile = hasRouteFile ? routeConfigPath : routeTempPath;
单独抽成了 getRoutes 工具函数

2020-04-15 12:24 UTC, chenbin92 commented on packages/plugin-store/src/babelPluginReplacePath.ts
> +            if (typeof value === 'string') {
fixed

2020-04-15 12:24 UTC, chenbin92 commented on packages/plugin-store/src/babelPluginReplacePath.ts
> +            if (value.startsWith("@/pages") || value.startsWith("../pages")) {
fixed

2020-04-15 12:31 UTC, ClarkXia commented on packages/plugin-store/src/babelPluginReplacePath.ts
> +                const matchedAliasKey = matchAliasKey(alias, value);
```json
alias: {
  "@": "./src",
  "@page": "./scr/pages"
}
```

这种 case 能够覆盖到吗

2020-04-16 13:45 UTC, ClarkXia requested changes

2020-04-16 13:45 UTC, ClarkXia commented on packages/plugin-store/src/babelPluginReplacePath.ts
> +  const flag = '../pages/';
相对地址应该是计算出来的

2020-04-17 04:12 UTC, ClarkXia approved these changes

2020-04-17 04:13 UTC, merged