[WIP] Feat/support plugin types
ice-lab/icejs pull request #48
Opened 2020-02-23 08:45 UTC by chenbin92

issue: https://github.com/ice-lab/icejs/issues/4

2020-02-24 08:44 UTC, ClarkXia commented
各个插件导出的类型都挂在 IAppConfig 上？上面应该挂的是配置的类型吧，RouterProps 那个类型挂上应该是有问题的

2020-02-24 08:46 UTC, ClarkXia commented
实现上有点像注册 appConfig 配置？然后注册的时候需要定义好类型

2020-02-24 08:52 UTC, chenbin92 commented
> 各个插件导出的类型都挂在 IAppConfig 上？上面应该挂的是配置的类型吧，RouterProps 那个类型挂上应该是有问题的

1. 需要挂载到 IAppConfig 的就挂载到 IAppConfig 上，如果不需要但是需要导出的也可以默认导出当前的插件的 types。
2. 最终的 types 是由插件添加然后统一导出的

```ts
// 需要挂载到 IAppConfig 上的使用方法
 applyMethod('addIceTypesExport', { source: `./${exportName}/types`, specifier: '{ ILogger }', exportName: `${exportName}?: ILogger` });

// 不挂载到 IAppConfig 上，但是需要导出插件的 types 的

 applyMethod('addIceTypesExport', { source:  './router/types' });
```

2020-02-24 08:53 UTC, chenbin92 commented
> 实现上有点像注册 appConfig 配置？然后注册的时候需要定义好类型

对的

2020-02-24 08:59 UTC, ClarkXia requested changes

2020-02-24 08:59 UTC, ClarkXia commented on packages/plugin-router/src/index.ts
> +  applyMethod('addIceTypesExport', { source: './router/types', specifier: '{ RouterProps }', exportName: 'router?: RouterProps' });
RouterProps 定义了是每一个 Route 项的属性，而 appConfig 上面的 router 支持的配置是 { type, modifyRoute } 这种

2020-02-24 09:06 UTC, ClarkXia commented
> 1. 需要挂载到 IAppConfig 的就挂载到 IAppConfig 上，如果不需要但是需要导出的也可以默认导出当前的插件的 types。

现在的导出都在 IAppConfig 下面

2020-02-24 09:07 UTC, chenbin92 commented on packages/plugin-router/src/index.ts
> +  applyMethod('addIceTypesExport', { source: './router/types', specifier: '{ RouterProps }', exportName: 'router?: RouterProps' });
看 RouterProps 定义如下是支持 type 的，可能需要新定义一个集成然后补充 modifyRoute 这种 API 了

![image](https://user-images.githubusercontent.com/3995814/75139602-01e03280-5728-11ea-9eab-816e94b79e40.png)

2020-02-24 09:15 UTC, chenbin92 commented
> > 1. 需要挂载到 IAppConfig 的就挂载到 IAppConfig 上，如果不需要但是需要导出的也可以默认导出当前的插件的 types。
> 
> 现在的导出都在 IAppConfig 下面

因为现在的实现需求就是定义 IAppConfig 的 types ，详见 https://github.com/ice-lab/icejs/issues/4#issue-565076014

![image](https://user-images.githubusercontent.com/3995814/75140033-1113b000-5729-11ea-90c2-12c6308f9fd6.png)

2020-02-24 09:20 UTC, ClarkXia commented
如果要使用 IRoutes 类型，现在是不是没地方导出？

2020-02-24 09:22 UTC, chenbin92 commented
> 如果要使用 IRoutes 类型，现在是不是没地方导出？

看这个评论 https://github.com/ice-lab/icejs/pull/48#issuecomment-590220298 第二种方式支持导出 

改动代码：https://github.com/ice-lab/icejs/pull/48/files#diff-64a51ed7dc8d52598b92574f0b0f1f11R13

2020-02-24 09:32 UTC, ClarkXia commented on packages/plugin-router/src/index.ts
> +  applyMethod('addIceTypesExport', { source: './router/types', specifier: '{ RouterProps }', exportName: 'router?: RouterProps' });
目前 router 的配置和 RouterProps 不是对应的，比如 routes 这项肯定不会开放出去进行配置

2020-02-24 12:11 UTC, chenbin92 commented on packages/plugin-router/src/index.ts
> +  applyMethod('addIceTypesExport', { source: './router/types', specifier: '{ RouterProps }', exportName: 'router?: RouterProps' });
根据 IAppConfig 支持的配置项重新定义一个 Interface

2020-03-03 14:51 UTC, chenbin92 commented on packages/plugin-router/src/index.ts
> +  applyMethod('addIceTypesExport', { source: './router/types', specifier: '{ RouterProps }', exportName: 'router?: RouterProps' });
更新了

2020-03-03 14:52 UTC, chenbin92 commented
@ClarkXia 在看下，相关评论已更新

2020-03-05 08:52 UTC, ClarkXia approved these changes

2020-03-05 08:52 UTC, merged