fix: compatible with lazy
ice-lab/icejs pull request #96
Opened 2020-03-11 02:05 UTC by chenbin92

* https://github.com/ice-lab/icejs/issues/91

2020-03-11 05:21 UTC, imsobear commented on yarn.lock
> +  integrity sha1-MkpTWERHVbWKnfLfZRVkPf8HU10=
what happened?

2020-03-11 09:12 UTC, chenbin92 commented on yarn.lock
> +  integrity sha1-MkpTWERHVbWKnfLfZRVkPf8HU10=
fixed

2020-03-11 10:11 UTC, ClarkXia commented
理论上 component 为空的话应该不进入到 getRouteComponent 逻辑，之前的逻辑默认不带 redirect 属性的情况下 component 就非空，要看下是不是有漏掉的场景

2020-03-11 10:13 UTC, chenbin92 commented
> 理论上 component 为空的话应该不进入到 getRouteComponent 逻辑，之前的逻辑默认不带 redirect 属性的情况下 component 就非空，要看下是不是有漏掉的场景

看那个 issue，就是用户只配置了 `path: '*'` 没有配置 component 的情况

2020-03-11 11:05 UTC, ClarkXia requested changes

2020-03-11 11:05 UTC, ClarkXia commented on packages/plugin-router/src/runtime/Router.tsx
> +  const { __LAZY__, dynamicImport }: IDynamicImportComponent = component || {};
> 看那个 issue，就是用户只配置了 path: '*' 没有配置 component 的情况

所以目前 `component || {}` 可能还是会有问题，在 component 是 undefined 的情况下，如果 routerWrappers 不为空，将会执行 wrapperRoute 中的相应逻辑

2020-03-12 12:58 UTC, chenbin92 commented on packages/plugin-router/src/runtime/Router.tsx
> +  const { __LAZY__, dynamicImport }: IDynamicImportComponent = component || {};
>  component 是 undefined 的情况下，如果 routerWrappers 不为空，将会执行 wrapperRoute 中的相应逻辑

在 wrapperRoutes 的位置做了判断，只有 component 存在时才会 wrapper


![image](https://user-images.githubusercontent.com/3995814/76523862-151f2c00-64a4-11ea-80d8-3f3a4d236658.png)

2020-03-12 13:01 UTC, ClarkXia approved these changes

2020-03-12 13:02 UTC, merged